import type { Metadata } from "next";
import localFont from "next/font/local";
import { Manrope } from "next/font/google";
import "./globals.css";

import ClientRoot from "./components/ClientRoot";
import Navbar from "./components/Navbar";
import Footer from "./sections/Footer";

const richmond = localFont({
  src: [
    { path: "../public/fonts/Richmond-Display-Light.woff2" },
    { path: "../public/fonts/Richmond-Display-Light.woff" },
  ],
  variable: "--font-richmond",
  display: "swap",
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Portfolio | Anuj Kumar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${richmond.variable} ${manrope.variable} antialiased`}>
        <ClientRoot />

        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
