import gsap from "gsap";

import { ScrollTrigger, SplitText } from "gsap/all";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Manrope } from "next/font/google";
import { ReactLenis } from "@/app/util/lenis";
import "./globals.css";

import ScrollManager from "./components/ScrollManager";
import InitialScrollSetup from "./components/InitialScrollSetup";
import Footer from "./sections/Footer";

gsap.registerPlugin(ScrollTrigger, SplitText);

const richmond = localFont({
  src: [
    {
      path: "../public/fonts/Richmond-Display-Light.woff2",
      style: "normal",
    },
    {
      path: "../public/fonts/Richmond-Display-Light.woff",
      style: "normal",
    },
  ],
  variable: "--font-richmond",
  display: "swap",
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Portfolio | Anuj Kumar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body
          className={`${richmond.variable} ${manrope.variable} antialiased`}
        >
          <InitialScrollSetup />
          <ScrollManager />
          {children}
          <Footer />
        </body>
      </ReactLenis>
    </html>
  );
}
