import type { Metadata } from "next";
import localFont from "next/font/local";
import { Manrope } from "next/font/google";
import "./globals.css";

const richmond = localFont({
    src: [
        {
            path: "../assets/fonts/Richmond-Display-Light.woff2",
            style: "normal",
        },
        {
            path: "../assets/fonts/Richmond-Display-Light.woff",
            style: "normal",
        },
    ],
    variable: "--font-display",
    display: "swap",
});

const manrope = Manrope({
    subsets: ["latin"],
    variable: "--font-sans",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${richmond.variable} ${manrope.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
